name: Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: actions/setup-node@v3      
        with:
          python-version: 3.x
          node-version: 16
      - run: pip install mkdocs-material mkdocs-git-revision-date-localized-plugin pygments pymdown-extensions
      - run: npm install -g workbox-cli
      - run: mkdocs gh-deploy --force